pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS = credentials('dockerhub')
	}

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t ${DOCKERHUB_DASHBOARD_IMAGE_NAME}:${DASHBOARD_IMAGE_TAG} -f ./Dockerfile .'
            }
        }
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push ${DOCKERHUB_DASHBOARD_IMAGE_NAME}:${DASHBOARD_IMAGE_TAG}'
            }
        }
    }
    post {
        always {
            emailext (
                to: '$DEFAULT_RECIPIENTS',
                subject: '$DEFAULT_SUBJECT',
                body: '$DEFAULT_CONTENT'
            )

            discordSend (
                webhookURL: "${DISCORD_WEBHOOK_URL}",
                title: "${JOB_NAME} #${BUILD_NUMBER} - Image ${DOCKERHUB_DASHBOARD_IMAGE_NAME}:${DASHBOARD_IMAGE_TAG}",
                description: "Build: ${BUILD_NUMBER}\nStatus: ${currentBuild.currentResult.toLowerCase()}",
                footer: "Build Duration: ${currentBuild.durationString}",
                result: currentBuild.currentResult,
                link: BUILD_URL,
            )

            sh 'docker logout'
        }
    }
}